services:
  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: vphone-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - ./ssl/webroot:/var/www/certbot
    command: >
      sh -c "
        if [ ! -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then
          echo 'Obtaining SSL certificate for ${DOMAIN}...';
          certbot certonly --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} -d www.${DOMAIN};
        else
          echo 'SSL certificate already exists for ${DOMAIN}';
        fi
      "

  # Nginx with SSL support
  nginx-ssl:
    image: nginx:alpine
    container_name: vphone-nginx-ssl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_var:/var/lib/letsencrypt:ro
      - ./ssl/webroot:/var/www/certbot:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - vphone-network
    environment:
      - DOMAIN=${DOMAIN}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # SSL renewal cron job
  certbot-renewal:
    image: certbot/certbot:latest
    container_name: vphone-certbot-renewal
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - ./ssl/webroot:/var/www/certbot
    command: >
      sh -c "
        while true; do
          echo 'Checking SSL certificate renewal...';
          certbot renew --webroot --webroot-path=/var/www/certbot --quiet;
          echo 'Sleeping for 12 hours...';
          sleep 43200;
        done
      "
    restart: unless-stopped

# Additional volumes for SSL
volumes:
  certbot_certs:
    driver: local
  certbot_var:
    driver: local

networks:
  vphone-network:
    external: true 