version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: vphone-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb-data/vphone-complete-backup:/docker-entrypoint-initdb.d/backup:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: vphone_admin
      MONGO_INITDB_ROOT_PASSWORD: vphone_secure_2024
      MONGO_INITDB_DATABASE: vphone
    networks:
      - vphone-network
    command: --wiredTigerCacheSizeGB 1.0

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vphone-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://vphone_admin:vphone_secure_2024@mongodb:27017/vphone?authSource=admin
      JWT_SECRET: vphone2024!secure#key$app
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: vphone24h3@gmail.com
      EMAIL_PASS: ftxhkismjvdqzawp
    depends_on:
      - mongodb
    networks:
      - vphone-network

  # Frontend Web App
  frontend:
    build: 
      context: ./iphone-inventory
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://app.vphone.vn/api
    container_name: vphone-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - vphone-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: vphone-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - vphone-network

networks:
  vphone-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local 