#!/bin/bash

# VPhone Production Setup for Nguyenkieuanh.com
echo "🚀 Setting up VPhone for production domain: Nguyenkieuanh.com"

# Create .env file for production
cat > .env << EOF
# VPhone Production Configuration for Nguyenkieuanh.com
# Domain Configuration
DOMAIN=Nguyenkieuanh.com
SSL_EMAIL=admin@nguyenkieuanh.com

# MongoDB Configuration  
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=@654321
MONGO_DB_NAME=vphone_production

# JWT Secret (generate a strong one for production)
JWT_SECRET=VPhone2025!ProductionJWT#NguyenKieuAnh\$SecureKey

# Email Configuration (sử dụng email hiện tại)
EMAIL_USER=vphone24h3@gmail.com
EMAIL_PASS=ftxhkismjvdqzawp

# Production Environment
NODE_ENV=production
EOF

echo "✅ Created .env file with production configuration"

# Update Dockerfile build args for production domain
echo "🔧 Updating frontend build configuration..."

# Stop any running containers
echo "🛑 Stopping existing containers..."
docker compose down

# Clean up old images
echo "🧹 Cleaning up old images..."
docker compose build --no-cache

# Start production environment
echo "🚀 Starting production environment..."
docker compose up -d

echo ""
echo "🎉 Production setup complete!"
echo ""
echo "📋 Production Information:"
echo "   Domain: https://Nguyenkieuanh.com"
echo "   Admin Email: admin@nguyenkieuanh.com"
echo "   Admin Username: admin"
echo "   Admin Password: 123456"
echo ""
echo "🔐 SSL Certificate:"
echo "   - Will be automatically generated by Let's Encrypt"
echo "   - Contact email: admin@nguyenkieuanh.com"
echo ""
echo "📝 Next steps:"
echo "   1. Make sure domain Nguyenkieuanh.com points to this server"
echo "   2. Wait for SSL certificate generation (may take a few minutes)"
echo "   3. Access https://Nguyenkieuanh.com to use the system"
echo ""
echo "📊 Monitor logs:"
echo "   docker compose logs -f"
echo "" 