#!/bin/bash

echo "🔍 KIỂM TRA DEPLOYMENT TRÊN VPS"
echo "================================"

echo "📋 HƯỚNG DẪN: Chạy các lệnh này trên VPS để kiểm tra:"
echo ""

echo "1. Kiểm tra git status trên VPS:"
echo "cd ~/sites/nguyenkieuanh.com"
echo "git status"
echo "git log --oneline -3"
echo ""

echo "2. Kiểm tra file auth.js đã được cập nhật chưa:"
echo "grep -n 'username.*trim' backend/routes/auth.js"
echo "# Phải thấy dòng: username: (username && username.trim()) ? username.trim() : null"
echo ""

echo "3. Nếu chưa có, pull code mới:"
echo "git pull origin main"
echo ""

echo "4. Rebuild containers:"
echo "docker-compose down"
echo "docker-compose build --no-cache"
echo "docker-compose up -d"
echo ""

echo "5. Test sau khi rebuild:"
echo "curl -X POST https://nguyenkieuanh.com/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"email\": \"testuser\$(date +%s)@vphone.com\","
echo "    \"password\": \"123456\","
echo "    \"full_name\": \"Test User\","
echo "    \"role\": \"admin\","
echo "    \"branch_id\": \"686783939535a971dfe22f4f\""
echo "  }'"
echo ""

echo "🎯 KẾT QUẢ MONG ĐỢI:"
echo "================================"
echo "✅ git log phải thấy commit: 'Add: Hướng dẫn deploy cuối cùng với phân quyền hoàn chỉnh'"
echo "✅ grep phải thấy: 'username: (username && username.trim()) ? username.trim() : null'"
echo "✅ Tạo user phải thành công: '{\"message\":\"✅ Tạo tài khoản thành công\"}'"
echo ""

echo "🚨 NẾU VẪN LỖI:"
echo "================================"
echo "1. Kiểm tra git remote: git remote -v"
echo "2. Force pull: git reset --hard origin/main"
echo "3. Clear docker cache: docker system prune -a"
echo "4. Rebuild từ đầu: docker-compose build --no-cache"
echo ""

echo "📞 DEBUG INFO CẦN GỬI:"
echo "================================"
echo "Nếu vẫn lỗi, hãy gửi kết quả của:"
echo "1. git log --oneline -3"
echo "2. grep -n 'username.*trim' backend/routes/auth.js"
echo "3. docker logs vphone-backend --tail 20"
echo "4. curl test user creation" 