#!/bin/bash

echo "🚀 FORCE DEPLOY - Đảm bảo VPS có tất cả commits"
echo "================================"

echo "📋 CHẠY CÁC LỆNH NÀY TRÊN VPS:"
echo ""

echo "1. Backup current state (optional):"
echo "cd ~/sites/nguyenkieuanh.com"
echo "git branch backup-$(date +%Y%m%d-%H%M%S)"
echo ""

echo "2. Force reset to match remote:"
echo "git fetch origin"
echo "git reset --hard origin/main"
echo ""

echo "3. Verify we have the username fix commit:"
echo "git log --oneline -10 | grep -i username"
echo "# Should see: f47bf41 Fix: Sửa lỗi username null và thêm input username vào form"
echo ""

echo "4. Check if auth.js has the fix:"
echo "grep -n 'username.*trim' backend/routes/auth.js"
echo "# Should see: username: (username && username.trim()) ? username.trim() : null"
echo ""

echo "5. If still not there, force pull specific commit:"
echo "git fetch origin"
echo "git checkout f47bf41 -- backend/routes/auth.js"
echo "git checkout f47bf41 -- iphone-inventory/src/pages/QuanLyUser.jsx"
echo ""

echo "6. Rebuild containers:"
echo "docker-compose down"
echo "docker system prune -f"
echo "docker-compose build --no-cache"
echo "docker-compose up -d"
echo ""

echo "7. Test the fix:"
echo "curl -X POST https://nguyenkieuanh.com/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"email\": \"testuser\$(date +%s)@vphone.com\","
echo "    \"password\": \"123456\","
echo "    \"full_name\": \"Test User\","
echo "    \"role\": \"admin\","
echo "    \"branch_id\": \"686783939535a971dfe22f4f\""
echo "  }'"
echo ""

echo "🎯 EXPECTED RESULT:"
echo "================================"
echo "✅ Should return: {\"message\":\"✅ Tạo tài khoản thành công\"}"
echo "❌ Should NOT return: username null error"
echo ""

echo "🔍 DEBUG COMMANDS:"
echo "================================"
echo "If still failing, run these and send results:"
echo "1. git log --oneline -10"
echo "2. grep -A5 -B5 'username.*trim' backend/routes/auth.js"
echo "3. docker logs vphone-backend --tail 30"
echo "4. curl test result"
echo ""

echo "💡 ALTERNATIVE - Manual fix:"
echo "================================"
echo "If git is still problematic, manually edit backend/routes/auth.js:"
echo "Find line ~54 and change:"
echo "FROM: username: username || null,"
echo "TO:   username: (username && username.trim()) ? username.trim() : null,"
echo ""
echo "Then rebuild: docker-compose build --no-cache && docker-compose up -d" 