#!/bin/bash

echo "🚀 Deploying fixes to VPS..."

# Instructions for user to run on VPS
echo "📋 INSTRUCTIONS TO RUN ON VPS:"
echo "================================"
echo "1. SSH to your VPS"
echo "2. cd ~/sites/nguyenkieuanh.com"
echo "3. Run the following commands:"
echo ""
echo "# Pull latest code"
echo "git pull origin main"
echo ""
echo "# Rebuild containers"
echo "docker-compose down"
echo "docker-compose up --build -d"
echo ""
echo "# Wait for containers to start"
echo "sleep 10"
echo ""
echo "# Test the fix"
echo "curl -X GET https://nguyenkieuanh.com/api/test-user-creation"
echo ""
echo "# Test user creation with valid data"
echo "curl -X POST https://nguyenkieuanh.com/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"email\": \"testuser$(date +%s)@vphone.com\","
echo "    \"password\": \"123456\","
echo "    \"full_name\": \"Test User\","
echo "    \"role\": \"admin\","
echo "    \"branch_id\": \"686783939535a971dfe22f4f\""
echo "  }'"
echo ""
echo "================================"
echo ""
echo "🔧 Current status: Code has been committed and pushed to GitHub"
echo "📦 Latest commit includes:"
echo "  - ✅ Fixed username null error"
echo "  - ✅ Added username input field"
echo "  - ✅ Backend handles empty string -> null conversion"
echo "  - ✅ All return functionality routes are ready"
echo "  - ✅ Tab mặc định Quản lý User đổi thành 'Tất cả user'"
echo "  - ✅ Phân quyền Sổ quỹ chỉ cho admin và quản lý"
echo ""
echo "⚠️  VPS needs to pull the latest code and rebuild containers"
echo "💡 After deployment, both user creation and return functionality should work" 